name: Publish to npm

on:
  release:
    types: [created] # Trigger when you create a new GitHub Release

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Vital for tokenless publishing
    steps:
      - uses: actions/checkout@v6
      
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      - name: Install and Build
        run: |
          npm ci
          npm run build

      - name: Publish to npm
        run: npm publish --provenance --access public
        env:
          # This flag tells npm to use the OIDC token provided by GitHub
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}